### ISSUE TITLE
问题求助

### ISSUE THREAD

**Issue by Ruoqiao-F** [RobinLu1209/STAG-GCN#2]
您好，麻烦问一下data/dataset.npy和matrix.npy怎么获得，谢谢啦~

**Comment by RobinLu1209** [comment]
需要自己对didi的数据进行数据清洗和处理哦~你也可以对自己的数据进行处理，成为需要的数据格式。

**Comment by Ruoqiao-F** [comment]
十分感谢您的回复！！！想请问一下您是怎么处理的🥺 因为我也是下载的didi的数据。如果可以的话，想向您学习一下，十分感谢🙏！

发自我的iPhone

**Comment by RobinLu1209** [comment]
主要是先划定分析区域，然后是对一些传感器缺失数据情况进行判断，有选择的进行补全或删除。道路拓扑可以根据经纬度坐标或路名来进行道路连通判断~

----- 原始邮件 -----
发件人: "Ruoqiao-F" <notifications@github.com>
收件人: "RobinLu1209/STAG-GCN" <STAG-GCN@noreply.github.com>
抄送: "robinlu1209" <robinlu1209@sjtu.edu.cn>, "Comment" <comment@noreply.github.com>
发送时间: 星期二, 2020年 12 月 29日 下午 4:56:29
主题: Re: [RobinLu1209/STAG-GCN] 问题求助 (#2)

十分感谢您的回复！！！想请问一下您是怎么处理的🥺 因为我也是下载的didi的数据。如果可以的话，想向您学习一下，十分感谢🙏！

发自我的iPhone

> 在 2020年12月29日，下午4:50，Robin Lu <notifications@github.com> 写道：
> 
> ﻿
> 需要自己对didi的数据进行数据清洗和处理哦~你也可以对自己的数据进行处理，成为需要的数据格式。
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.


-- 
You are receiving this because you commented.
Reply to this email directly or view it on GitHub:
https://github.com/RobinLu1209/STAG-GCN/issues/2#issuecomment-752001129
-- 
卢彬/Robin Lu

上海交通大学电子信息与电气工程学院/School of Electronic Information and Electrical Engineering
/Shanghai Jiao Tong University
电子工程系/Department of Electronic Engineering  
智能物联网研究中心/Intelligent Internet of Things Center

手机/Cell: 15821334893
邮箱/Email: robinlu1209@sjtu.edu.cn

**Comment by Ruoqiao-F** [comment]
万分感谢~~！！！ 实在不好意思冒昧的问一下您，是否方便能发我一份您们处理好的数据学习一下呢？保证是用于科研学习！如果不便就不给您添麻烦了！ 










在 2020-12-29 17:49:06，"Robin Lu" <notifications@github.com> 写道：

主要是先划定分析区域，然后是对一些传感器缺失数据情况进行判断，有选择的进行补全或删除。道路拓扑可以根据经纬度坐标或路名来进行道路连通判断~

----- 原始邮件 -----
发件人: "Ruoqiao-F" <notifications@github.com>
收件人: "RobinLu1209/STAG-GCN" <STAG-GCN@noreply.github.com>
抄送: "robinlu1209" <robinlu1209@sjtu.edu.cn>, "Comment" <comment@noreply.github.com>
发送时间: 星期二, 2020年 12 月 29日 下午 4:56:29
主题: Re: [RobinLu1209/STAG-GCN] 问题求助 (#2)

十分感谢您的回复！！！想请问一下您是怎么处理的 因为我也是下载的didi的数据。如果可以的话，想向您学习一下，十分感谢！

发自我的iPhone

> 在 2020年12月29日，下午4:50，Robin Lu <notifications@github.com> 写道：
>
> ﻿
> 需要自己对didi的数据进行数据清洗和处理哦~你也可以对自己的数据进行处理，成为需要的数据格式。
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.


--
You are receiving this because you commented.
Reply to this email directly or view it on GitHub:
https://github.com/RobinLu1209/STAG-GCN/issues/2#issuecomment-752001129
--
卢彬/Robin Lu

上海交通大学电子信息与电气工程学院/School of Electronic Information and Electrical Engineering
/Shanghai Jiao Tong University
电子工程系/Department of Electronic Engineering
智能物联网研究中心/Intelligent Internet of Things Center

手机/Cell: 15821334893
邮箱/Email: robinlu1209@sjtu.edu.cn

**Comment by wanzhixiao** [comment]
您好，能发布一下数据的输入维度吗

**Comment by RobinLu1209** [comment]
邻接矩阵的数据维度是节点数*节点数
历史道路数据的维度是 时间片*（节点数+1）
加1的那个数据维度应该是无用的，主要是之前在算法设计的时候有一些别的考量，可以去掉，同时在geometric_dataset.py中做细微修改。
